services:
  bolt-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8787:8787"
    environment:
      - NODE_ENV=production
      - PORT=8787
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8787/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # Optionnel: pour persister les logs
      - ./logs:/app/logs
    networks:
      - bolt-network

  bolt-network:
    driver: bridge